# =====================================================
# OpenClash Ultimate++ 2026
# AI / Streaming / Gaming / Microsoft / DNS Secure
# =====================================================

mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: warning
ipv6: false
tcp-concurrent: true
unified-delay: true
client-fingerprint: chrome
geodata-mode: true

profile:
  store-selected: true
  store-fake-ip: true

# -----------------------------------------------------
# TUN
# -----------------------------------------------------

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53

# -----------------------------------------------------
# DNS
# -----------------------------------------------------

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  respect-rules: true
  cache-algorithm: arc
  ipv6: false

  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  proxy-server-nameserver:
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query

  nameserver:
    - https://dns.google/dns-query#🚀 默认代理
    - https://dns.cloudflare.com/dns-query#🚀 默认代理

  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - 211.142.211.124
    - 111.8.14.18

  fallback:
    - https://1.1.1.1/dns-query
    - https://8.8.4.4/dns-query

  fake-ip-filter:
    - "rule-set:fakeip-filter"

# -----------------------------------------------------
# 订阅
# -----------------------------------------------------

proxy-providers:

  Airport:
    type: http
    url: "你的订阅地址"
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300

proxies:
  - {name: 直连, type: direct}

# -----------------------------------------------------
# 策略组
# -----------------------------------------------------

proxy-groups:

# 默认
  - name: 🚀 默认代理
    type: select
    proxies:
      - ♻️ 自动选择
      - 🔯 美国故转
      - 🔯 日本故转
      - 🔯 新加坡故转
      - 🔯 香港故转
      - 🌐 全部节点
      - 直连

  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 默认代理
      - 直连

# AI 自动节点
  - name: 🤖 AI-AUTO
    type: url-test
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)us|japan|singapore|hk"

# AI 服务
  - name: 🤖 ChatGPT
    type: select
    proxies:
      - 🤖 AI-AUTO
      - 🔯 美国故转
      - 🚀 默认代理

  - name: 🤖 Claude
    type: select
    proxies:
      - 🤖 AI-AUTO
      - 🔯 美国故转

  - name: 🧠 Gemini
    type: select
    proxies:
      - 🤖 AI-AUTO
      - 🔯 日本故转

  - name: 🟣 Perplexity
    type: select
    proxies:
      - 🔯 美国故转
      - 🤖 AI-AUTO

  - name: 🗿 Grok
    type: select
    proxies:
      - 🔯 美国故转
      - 🤖 AI-AUTO

  - name: ♾️ MetaAI
    type: select
    proxies:
      - 🔯 美国故转
      - 🤖 AI-AUTO

# Streaming
  - name: 🎬 Netflix
    type: select
    proxies:
      - 🔯 新加坡故转
      - 🔯 日本故转
      - 🔯 美国故转
      - 🔯 香港故转

  - name: 🏰 Disney+
    type: select
    proxies:
      - 🔯 美国故转
      - 🔯 新加坡故转
      - 🔯 香港故转

  - name: 🎥 HBO
    type: select
    proxies:
      - 🔯 美国故转
      - 🚀 默认代理

  - name: 📦 Amazon
    type: select
    proxies:
      - 🚀 默认代理
      - 直连

# Microsoft
  - name: 🪟 Microsoft
    type: select
    proxies:
      - 🚀 默认代理
      - 直连

# Social
  - name: 📲 Telegram
    type: select
    proxies:
      - 🔯 香港故转
      - 🚀 默认代理

# TikTok
  - name: 🎵 TikTok
    type: select
    proxies:
      - 🔯 日本故转
      - 🔯 新加坡故转
      - 🔯 美国故转

# 自动节点
  - name: 🔯 美国故转
    type: fallback
    include-all: true
    interval: 300
    lazy: true
    filter: "(?i)us|america|美"

  - name: 🔯 日本故转
    type: fallback
    include-all: true
    interval: 300
    lazy: true
    filter: "(?i)japan|jp|日"

  - name: 🔯 新加坡故转
    type: fallback
    include-all: true
    interval: 300
    lazy: true
    filter: "(?i)singapore|sg|新"

  - name: 🔯 香港故转
    type: fallback
    include-all: true
    interval: 300
    lazy: true
    filter: "(?i)hong|hk|港"

  - name: ♻️ 自动选择
    type: url-test
    include-all: true
    interval: 300
    tolerance: 20

  - name: 🌐 全部节点
    type: select
    include-all: true

# -----------------------------------------------------
# 规则
# -----------------------------------------------------

rules:

  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,private_domain,直连

# AI
  - RULE-SET,openai,🤖 ChatGPT
  - RULE-SET,anthropic,🤖 Claude
  - RULE-SET,gemini,🧠 Gemini
  - RULE-SET,perplexity,🟣 Perplexity
  - RULE-SET,xai,🗿 Grok
  - RULE-SET,meta_ai,♾️ MetaAI

# Streaming
  - RULE-SET,netflix,🎬 Netflix
  - RULE-SET,disney,🏰 Disney+
  - RULE-SET,hbo,🎥 HBO
  - RULE-SET,amazon,📦 Amazon

# Microsoft
  - RULE-SET,microsoft,🪟 Microsoft

# Social
  - RULE-SET,telegram,📲 Telegram
  - RULE-SET,tiktok,🎵 TikTok

# Google
  - RULE-SET,google,🚀 默认代理

# Apple
  - RULE-SET,apple,直连

# 广告
  - RULE-SET,ads,REJECT

# 国内
  - RULE-SET,cn_domain,直连
  - RULE-SET,cn_ip,直连

# 国外
  - RULE-SET,geolocation-!cn,🚀 默认代理

  - MATCH,🐟 漏网之鱼

# -----------------------------------------------------
# 规则锚点
# -----------------------------------------------------

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}

rule-providers:

  fakeip-filter:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/fakeip-filter.mrs

  private_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs

  private_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs

  openai:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs

  anthropic:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/anthropic.mrs

  gemini:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-gemini.mrs

  perplexity:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/perplexity.mrs

  xai:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/xai.mrs

  meta_ai:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/meta.mrs

  microsoft:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs

  netflix:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs

  disney:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs

  hbo:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/hbo.mrs

  amazon:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/amazon.mrs

  telegram:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs

  tiktok:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs

  google:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs

  apple:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs

  ads:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs

  cn_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs

  cn_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs

  geolocation-!cn:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs
